import { PrismaClient } from "@prisma/client"

declare global {
  var prisma: PrismaClient | undefined
}

const client = globalThis.prisma || new PrismaClient()
//then create environment check
//this is meant to stop prisma clients from being generated by hot reload
if (process.env.NODE_ENV !== "production") globalThis.prisma = client

export default client